export class GetCardDetailsModel {
    HOTELID: number =0;
    RESID: number= 0;
    DEPARTMENTID: number =0;
    DEPCODE: string = "";
    DEPNAME: string="";
    DEPTTYPE: number=0;
    ELEKTRADEPTTYPE: string="";
    DEPTTYPENAME: string="";
    REVENUEID?: any;
    REVENUE?: any;
    REVENUENAME?: any;
    REVTYPE?: any;
    FOLIOINVOICEID?: any;
    FOLIODATE: string="";
    FOLIONOTE?: any;
    DOCNO?: any;
    TOTAL: number=0;
    CTOTAL: number=0;
    CURRENCY: string="";
    CURRENCYSIGN: string="";
    TYPEID: number=0;
    TYPE: string="";
    AGENCY?: any;
    AGENCYCODE: string="";
    GUESTNAMES: string="";
    ROOMNO: string="";
    ROOMTYPE: string="";
    GIVENROOMTYPEID: number=0;
    CHECKIN: string="";
    CHECKOUT: string="";
    VOUCHERNO?: any;
    LOGOURL: string="";
    SALESPROJECTID: number=0;
    ASSIGNTYPE: number=0;
    CURRENCYRATE: number=0;
    CREATION_DATE: string="";
    POSCHECKID?: any;
    ID: number=0;
    CURRATE: number=0;
    SOURCEID?: any;
    RESNAMEID: number=0;
    NAME: string="";
    LNAME: string="";
    CARDNO: string="";
}